"""drop unique index on avatar_url

Revision ID: 0d6fd6c67f9e
Revises: 301e8a60961c
Create Date: 2026-05-22 13:40:19.038241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d6fd6c67f9e'
down_revision = '301e8a60961c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_table_avatar_url_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_table', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('user_table_avatar_url_key'), ['avatar_url'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
